package com.supplychainx.supply_service.mapper;

import com.supplychainx.supply_service.dto.request.SupplierRequest;
import com.supplychainx.supply_service.dto.response.SupplierResponse;
import com.supplychainx.supply_service.model.Supplier;
import com.supplychainx.supply_service.model.SupplyOrder;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.factory.Mappers;

import java.util.List;
import java.util.stream.Collectors;

@Mapper(componentModel = "spring") // componentModel="spring" allows Spring to inject the mapper
public interface SupplierMapper {

    // Access to the generated mapper implementation
    SupplierMapper INSTANCE = Mappers.getMapper(SupplierMapper.class);

    // --- MAPPING FROM REQUEST DTO TO ENTITY (For Creation) ---
    // Note: We ignore the ID as it is generated by the database
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "supplyOrders", ignore = true) // Relationships ignored during basic create
    Supplier toEntity(SupplierRequest dto);

    // --- MAPPING FROM ENTITY TO RESPONSE DTO (For Retrieval) ---
    // We map the List<SupplyOrder> to List<Long> (list of IDs)
    @Mapping(target = "supplyOrderIds", expression = "java(mapSupplyOrdersToIds(entity.getSupplyOrders()))")
    SupplierResponse toResponse(Supplier entity);

    List<SupplierResponse> toResponseList(List<Supplier> entities);

    // --- Custom Mapping Logic (Needed for mapping List<SupplyOrder> to List<Long>) ---
    default List<Long> mapSupplyOrdersToIds(List<SupplyOrder> supplyOrders) {
        if (supplyOrders == null) {
            return List.of();
        }
        return supplyOrders.stream()
                .map(SupplyOrder::getId)
                .collect(Collectors.toList());
    }
}