package com.supplychainx.supply_service.mapper;

import com.supplychainx.supply_service.dto.request.UserRequest;
import com.supplychainx.supply_service.dto.response.UserResponse;
import com.supplychainx.supply_service.model.User;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

import java.util.List;

@Mapper(componentModel = "spring")
public interface UserMapper {

    // Maps UserRequest (DTO) to User (Entity).
    // The 'id' is ignored because it's generated by the database.
    @Mapping(target = "id", ignore = true)
    User toEntity(UserRequest request);

    // Maps User (Entity) to UserResponse (DTO).
    // The password field in the Entity is automatically ignored
    // since the UserResponse DTO does not have a 'password' field,
    // ensuring password security.
    UserResponse toResponse(User user);

    // Helper method to map a list of entities to a list of response DTOs
    List<UserResponse> toResponseList(List<User> users);
}